# Nombre del flujo de trabajo:
name: Despliegue Continuo

# Este flujo de trabajo se activa...
on:
  
  # Cuando se complete el flujo de trabajo 'Integración Continua' de forma
  # satisfactoria
  workflow_run:
    workflows: ["Integración Continua"]
    types:
      - completed

# Trabajos que se ejecutan en el flujo de trabajo
jobs:

  # Nombre del trabajo nº1
  Deploy_ECR:

    # Se ejecuta en una máquina con Ubuntu
    runs-on: ubuntu-24.04

    # Lista de pasos del 'job'
    steps:

    # Paso 1: Checkout del repositorio para tenerlo en local en la
    # máquina de Ubuntu
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    # Paso 2: Configurar credenciales de AWS
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # Paso 3: Instalar Terraform v1.9.8
    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    # Paso 4: Inicializar Terraform en el directorio 'infra' (donde están los
    # archivos de Terraform en el repositorio)
    - name: Inicializar Terraform
      working-directory: ./infra
      run: terraform init

    # Paso 5: Se genera el plan de ejecución de Terraform solo para el recurso
    # de ECR, guardando el plan en un archivo llamado 'tfplan' 
    - name: Plan de Terraform (solo ECR)
      working-directory: ./infra
      run: terraform plan -out=tfplan -target=module.ecr_weather_repo.aws_ecr_repository.weather_repo

    # Paso 6: Se aprovisiona solamente el recurso de ECR
    - name: Aplicar Terraform (solo ECR)
      working-directory: ./infra
      run: terraform apply -auto-approve tfplan

  # Nombre del trabajo nº2
  Build_Push_Imagen_Docker:

    # Se ejecuta en una máquina con Ubuntu
    runs-on: ubuntu-24.04

    # El trabajo se ejecuta solo cuando termine el trabajo nº1
    needs: Deploy_ECR

    # Lista de pasos del trabajo
    steps:

    # Paso 1: Checkout del repositorio
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    # Paso 2: Comprobar si el 'Dockerfile' o el 'main.py' se han modificado
    # entre el último y el penúltimo 'commit'
    # Se almacena en 'CHANGED_FILES' los nombres de los archivos modificados
    # entre el último (HEAD) y el penúltimo (HEAD^) 'commit' del repositorio.
    # Si en la variable se almacenan el nombre del 'Dockerfile' o del 'main'
    # de la aplicación web es que se han modificado, y por tanto, la variable
    # 'run_build' es true, indicando que se deben ejecutar los pasos para la
    # construcción y subida de la imagen Docker.
    # Por último, el valor de la variable 'run_build' se pasa a la variable de
    # entorno 'GITHUB_ENV' para que su valor esté disponible en pasos
    # posteriores de este trabajo.
    - name: Comprobar si se han modificado el 'Dockerfile' o la webapp de Streamlit
      id: check_changes
      run: |
        git fetch --depth=2
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Archivos modificados: $CHANGED_FILES"

        if [[ "$CHANGED_FILES" == *"src/web_application/Dockerfile"* || "$CHANGED_FILES" == *"src/web_application/main.py"* ]]; then
          echo "Cambios detectados en Dockerfile o main.py"
          echo "run_build=true" >> $GITHUB_ENV
        else
          echo "No hay cambios relevantes para la imagen Docker"
          echo "run_build=false" >> $GITHUB_ENV
        fi

    # Paso 3: Configurar credenciales de AWS
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # Paso 4: Autenticación en Amazon ECR de nuestra cuenta (solo si 'run_build' es true)
    - name: Autenticarse en Amazon ECR
      if: env.run_build == 'true'
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com

    # Paso 5: Construir la imagen Docker (solo si 'run_build' es true)
    - name: Construir la imagen Docker
      if: env.run_build == 'true'
      run: docker build -t streamlit-app:1.0 ./src/web_application

    # Paso 6: Etiquetar la imagen Docker para el repositorio ECR (solo si 'run_build' es true)
    - name: Etiquetar la imagen Docker
      if: env.run_build == 'true'
      run: docker tag streamlit-app:1.0 ${{ secrets.ACCOUNT_AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com/weather_web_application:1.0

    # Paso 7: Subir la imagen Docker a ECR (solo si 'run_build' es true)
    - name: Subir la imagen Docker a ECR
      if: env.run_build == 'true'
      run: docker push ${{ secrets.ACCOUNT_AWS_ID }}.dkr.ecr.us-east-1.amazonaws.com/weather_web_application:1.0

  # Nombre del trabajo nº3
  Despliegue_Terraform:

    # Se ejecuta en una máquina con Ubuntu
    runs-on: ubuntu-24.04

    # El trabajo se ejecuta solo cuando termine el trabajo 'Build_Push_Imagen_Docker'
    needs: Build_Push_Imagen_Docker

    # Lista de pasos del trabajo
    steps:

    # Paso 1: Configuración del repositorio
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    # Paso 2: Configurar el acceso a AWS Academy usando los secretos
    # del repositorio con las credenciales de AWS
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # Paso 3: Instalar Terraform v1.9.8
    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    # Paso 4: Inicializar Terraform en el directorio 'infra' (donde están los
    # archivos de Terraform en el repositorio)
    - name: Inicializar Terraform
      working-directory: ./infra
      run: terraform init

    # Paso 5: Generar el plan de ejecución de Terraform en el directorio
    # 'infra', guardando el plan en un archivo llamado 'tfplan' y pasando
    # el valor de la 'API KEY' guardado como secreto en el repositorio del
    # proyecto
    - name: Plan de Terraform
      working-directory: ./infra
      run: terraform plan -out=tfplan -var "openweather_api_key=${{ secrets.API_KEY }}"

    # Paso 6: Aplicar el plan de Terraform guardado en 'tfplan' si se aplica
    # el 'commit' en a la rama 'master'
    - name: Aplicar el plan de Terraform
      working-directory: ./infra
      if: github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve tfplan